name: Bump version
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/modules/**'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'  
    - name: Check for changes in submodules
      id: submodules_changes
      run: |
        pre=""
        for dir in terraform/modules/**; do
          if [[ -n $(git diff HEAD~1 -- $dir) ]]; then
            echo "Changes detected in submodule: $dir"
            splitDir=$(echo $dir | awk -F/ '{print $(NF-1)}')
            echo $splitDir        
            pre+=$splitDir
            pre+="-"
          fi
        done
        echo prefix=$pre >> $GITHUB_OUTPUT
        echo "this is the new value for pre: $pre"
        
    - name: Bump version and push tag
      id: bump-version
      uses: Eliohoyeck/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        TAG_PREFIX: ${{steps.submodules_changes.outputs.prefix}}
        BRANCH_HISTORY: 'last'

    - name: test1
      id: testing
      run: |
        echo ${{steps.bump-version.outputs.new_tag}}
        echo ${{steps.bump-version.outputs.outputcommit}}
        echo ${{steps.bump-version.outputs.outputauthor}}
        
    - name: Append to markdown file
      if: success()
      run: |
        printf "\n" >> temp.md
        echo -e "-------------------------------------------------------------" >> temp.md
        printf "\n" >> temp.md
        printf -- "${{steps.bump-version.outputs.outputauthor}}<br></br>\n [commit](https://github.com/Eliohoyeck/terraform-aws-privatemodule/commit/${{steps.bump-version.outputs.outputcommit}})<br></br>\n ${{steps.bump-version.outputs.new_tag}}<br></br>\n" >> temp.md
        printf "\n" >> temp.md
        cat temp.md modules-version.md > mynewfile.md
        mv mynewfile.md modules-version.md

    - name: Delete tag   # this job only runs if the previous job failed, in this case it will delete the previously creted tag in case of error
      if: failure()
      run: |
        git tag -d ${{steps.bump-version.outputs.new_tag}}
        git push origin :refs/tags/${{steps.bump-version.outputs.new_tag}}  
        
    - name: Commit changes
      if: success()    
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"  
        git add myfile.md
        git commit -m "Append outputs to myfile.md"
        git push
        id: commit_changes        


    - name: Delete tag   # this job only runs if the previous job failed, in this case it will delete the previously creted tag in case of error
      run: |
        git tag -d ${{steps.bump-version.outputs.new_tag}}
        git push origin :refs/tags/${{steps.bump-version.outputs.new_tag}}  
        if: steps.commit_changes.outputs.exit_code != 0
