name: Bump version
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/modules/**'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'  
        
    - name: Bump version and push tag
      id: bump-version
      uses: Eliohoyeck/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        BRANCH_HISTORY: 'last'
        MODULES_PATH: 'terraform/modules/*/**'
        
