name: Bump version
on:
  push:
    branches:
      - main
    paths:
      - 'modules/**'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'  
    - name: Check for changes in submodules
      run: |
        for dir in modules/**; do
        echo $dir
        echo $GITHUB_SHA
        commit=$(git rev-parse HEAD)
        prevCommit=$(git rev-parse HEAD~1)
        echo "this is the commit: $commit"
        echo "this is the prev commit: $prevCommit"
          if [[ -n $(git diff HEAD~1 -- $dir) ]]; then
            echo "Changes detected in submodule: $dir"
            exit 0
          fi
        done
        
    # - name: Set prefix
    #   run: |
    #     prefix=""
    #     for path in ${{github.event.head_commit.modified}}; do
    #       if [[ $path == modules/* ]]; then
    #         prefix=$(echo $path | cut -d'/' -f3)
    #         break
    #       fi
    #     done
    #     echo "Tag prefix: $prefix"
        

    - name: Bump version and push tag
      id: bump-version
      uses: Eliohoyeck/github-tag-action-elio@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    #   TAG_PREFIX: 'v'
        BRANCH_HISTORY: 'last'
    # - name: Create custom tag
    #   shell: bash
    #   run: |
    #     tag=$prefix-${{ steps.bump_version_and_push_tag.outputs.tag }}
    #     echo "Custom tag: $new_tag"
    #   env:
    #     CUSTOM_TAG: $new_tag
    # - name: Create new tag
    #   run: git tag env.CUSTOM_TAG
