name: Bump version
on:
  push:
    branches:
      - main
    paths:
      - 'modules/**'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Get modified folders
      id: modified_folders
      run: |
        modified_folders=$(git diff --name-only HEAD HEAD~1 terraform/modules/eks terraform/modules/azure)
        if [ -n "$modified_folders" ]; then
          echo "Modified folders: $modified_folders"
          folder=$(echo "$modified_folders" | cut -d/ -f3)
          echo "folder: $folder"
        else
          echo "No files were modified"
        fi
    # - name: Set prefix
    #   run: |
    #     prefix=""
    #     for path in ${{github.event.head_commit.modified}}; do
    #       if [[ $path == modules/* ]]; then
    #         prefix=$(echo $path | cut -d'/' -f3)
    #         break
    #       fi
    #     done
    #     echo "Tag prefix: $prefix"
        
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: bump-version
      uses: Eliohoyeck/github-tag-action-elio@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    #   TAG_PREFIX: 'v'
        BRANCH_HISTORY: 'last'
    # - name: Create custom tag
    #   shell: bash
    #   run: |
    #     tag=$prefix-${{ steps.bump_version_and_push_tag.outputs.tag }}
    #     echo "Custom tag: $new_tag"
    #   env:
    #     CUSTOM_TAG: $new_tag
    # - name: Create new tag
    #   run: git tag env.CUSTOM_TAG
