name: Version Module

on:
  push:
    branches:
      - main
    paths:
      - 'modules/**'

jobs:
  version-module:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install packages
      run: npm ci

    - name: Install version-incrementer package
      run: npm install version-incrementer

    - name: Create Tag
      run: |
        let version = '2.0.0';
        let incrementedVersion;
        while (version !== '10.0.0') {
          incrementedVersion = version.split(".");
          if (incrementedVersion[2] !== '9') {
            incrementedVersion[2] = (parseInt(incrementedVersion[2]) + 1).toString();
          }else if(incrementedVersion[1] !== '9'){
            incrementedVersion[1] = (parseInt(incrementedVersion[1]) + 1).toString();
            incrementedVersion[2] = '0';
          }else{
            incrementedVersion[0] = (parseInt(incrementedVersion[0]) + 1).toString();
            incrementedVersion[1] = '0';
            incrementedVersion[2] = '0';
          }
          version = incrementedVersion.join(".");
          npm version ${version} --no-git-tag-version
          git tag -a ${version} -m "Tag created by Github Actions"
          git push origin ${version}