name: Version Module

on:
  push:
    branches:
      - main
    paths:
      - 'modules/**'

jobs:
  version-module:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install packages
      run: npm ci

    - name: Install version-incrementer package
      run: npm install version-incrementer

    - name: Create Tag
      run: |
        const VersionIncrementer = require('version-incrementer');
        const incrementer = new VersionIncrementer();
        let version = '1.0.0';
        let incrementedVersion;
        while (version !== '10.0.0') {
          incrementedVersion = incrementer.increment(version, 'patch');
          if (incrementedVersion.endsWith('9.9')) {
            incrementedVersion = incrementer.increment(version, 'minor');
          }
          if (incrementedVersion.endsWith('.9')) {
            incrementedVersion = incrementer.increment(version, 'major');
          }
          version = incrementedVersion;
          git tag -a $version -m "Tag created by Github Actions"
          git push origin $version
        }