name: Bump version
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'terraform/modules/**'
      
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
  
jobs:
  build:
    runs-on: ubuntu-22.04   
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        id: bump-version
        uses: Eliohoyeck/module-versioning-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODULES_PATH: 'terraform/modules/*/**'
          #MAJOR_STRING_TOKEN: 'major'
          #MINOR_STRING_TOKEN: 'minor'
          #PATCH_STRING_TOKEN: 'patch'

      - name: Changelog
        run: |
          branch_suffix=$RANDOM
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git checkout -b changelog-$branch_suffix
          git add modules-versions.md
          git commit -m "Update changelog"
          git push --set-upstream origin changelog-$branch_suffix
          gh pr create --title "Update changelog" --body "Please review and approve this changelog update." --base main --head changelog-$branch_suffix
          # Get the PR number
          PR_NUMBER=$(gh pr list --base main | grep changelog-$branch_suffix | awk '{print $1}')
          echo "::set-output name=pr_number::$PR_NUMBER"

      - name: Get Slack ID
        id: get_id
        run: |
          SLACK_IDS=$(cat slack_ids.json)
          echo "::set-output name=slack_id::$(echo $SLACK_IDS | jq -r .${{ github.actor }})"
        
      - name: Send notification to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "New PR opened"
          SLACK_MESSAGE: "<@${{ steps.get_id.outputs.slack_id }}> A new PR for changelog has been opened. Please review and approve. https://github.com/<YourGitHubUserName>/<YourRepositoryName>/pull/${{ steps.changelog.outputs.pr_number }}"
          SLACK_USERNAME: GithubActions
          SLACK_ICON_EMOJI: ":bell:"
          SLACK_COLOR: "#36a64f"        
