name: Bump version
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/modules/**'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'  
        
    - name: Bump version and push tag
      id: bump-version
      uses: Eliohoyeck/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        TAG_PREFIX: ${{steps.submodules_changes.outputs.prefix}}
        BRANCH_HISTORY: 'last'

        
    - name: Publish output artifact
      uses: actions/upload-artifact@v3
      with:
        name: modules-versions
        path: modules-versions.md
        
    - name: Commit changes
      if: always()
      id: commit_changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"  
        git add modules-versions.md
        git commit -m "Append outputs to modules-versions.md"
        git push
              
    - name: Delete tag on fail commit # this step will only get triggered if a tag exists and if commit_changes fails
      if: failure()
      id: delete_if_fail_commit
      run: |
        if [[ $(git tag -l ${{steps.bump-version.outputs.new_tag}}) ]]; then
          git tag -d ${{steps.bump-version.outputs.new_tag}}
          git push origin :refs/tags/${{steps.bump-version.outputs.new_tag}}  
        fi    
