name: Bump version
on:
  push:
    branches:
      - main
    paths:
      - 'modules/**'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'  
    - name: Check for changes in submodules
      id: submodules_changes
      run: |
        prefix=""
        for dir in modules/**; do
          if [[ -n $(git diff HEAD~1 -- $dir) ]]; then
            echo "Changes detected in submodule: $dir"
            splitDir=$(echo $dir | cut -d "/" -f 2)
            echo $splitDir        
            prefix+=$splitDir
          fi
        done
        echo $prefix >> $GITHUB_OUTPUT
        
    - name: Set prefix
      run: |
        echo ${{steps.submodules_changes.outputs.prefix}}
        

    - name: Bump version and push tag
      id: bump-version
      uses: Eliohoyeck/github-tag-action-elio@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    #    TAG_PREFIX: $prefix
        BRANCH_HISTORY: 'last'
    # - name: Create custom tag
    #   shell: bash
    #   run: |
    #     tag=$prefix-${{ steps.bump_version_and_push_tag.outputs.tag }}
    #     echo "Custom tag: $new_tag"
    #   env:
    #     CUSTOM_TAG: $new_tag
    # - name: Create new tag
    #   run: git tag env.CUSTOM_TAG
