name: Bump version
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'terraform/modules/**'
      
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
  
jobs:
  build:
    runs-on: ubuntu-22.04   
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        id: bump-version
        uses: Eliohoyeck/module-versioning-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODULES_PATH: 'terraform/modules/*/**'
          #MAJOR_STRING_TOKEN: 'major'
          #MINOR_STRING_TOKEN: 'minor'
          #PATCH_STRING_TOKEN: 'patch'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run release-it
        run: npx release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
