name: Bump version
on:
  push:
    branches:
      - main
    paths:
      - 'modules/**'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'  
    - name: Check for changes in submodules
      id: submodules_changes
      run: |
        pre=""
        for dir in modules/**; do
          if [[ -n $(git diff HEAD~1 -- $dir) ]]; then
            echo "Changes detected in submodule: $dir"
            splitDir=$(echo $dir | cut -d "/" -f 2)
            echo $splitDir        
            pre+=$splitDir
            pre+="-"
          fi
        done
        echo prefix=$pre >> $GITHUB_OUTPUT
        echo "this is the new value for pre: $pre"
        
    - name: Bump version and push tag
      id: bump-version
      uses: Eliohoyeck/github-tag-action-elio@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        TAG_PREFIX: ${{steps.submodules_changes.outputs.prefix}}
        BRANCH_HISTORY: 'last'

    - name: test1
      id: testing
      run: |
        echo ${{steps.bump-version.outputs.new_tag}}
        echo ${{steps.bump-version.outputs.outputcommit}}
        echo ${{steps.bump-version.outputs.outputauthor}}
        
    - name: Append to markdown file
      run: |
    - name: Append to markdown file
      run: |
    - name: Append to markdown file
      run: |
        echo -e "${{steps.bump-version.outputs.new_tag}} \n ${{steps.bump-version.outputs.outputcommit}} \n ${{steps.bump-version.outputs.outputauthor}}" >> myfile.md
        sed -i '1!G;h;$!d' myfile.md

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"  
        git add myfile.md
        git commit -m "Append outputs to myfile.md"
        git push
       
    # - name: Create custom tag
    #   shell: bash
    #   run: |
    #     tag=$prefix-${{ steps.bump_version_and_push_tag.outputs.tag }}
    #     echo "Custom tag: $new_tag"
    #   env:
    #     CUSTOM_TAG: $new_tag
    # - name: Create new tag
    #   run: git tag env.CUSTOM_TAG
